server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.gnawococ.springcloud.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-dept
  datasource:
    username: root
    password: username
    url: jdbc:mysql://127.0.0.1:3306/clouddb02?serverTimezone=GMT&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:  #将客服端注册进eureka列表中
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8002 #自定义服务器名称信息
    prefer-ip-address: true  #访问路径可以显示ip

#eureka对info信息的改善
info:
  app.name: gnawococ-microservicecloud
  company.name: www.gnawococ.com
  build.artifactId: microservicecloud-provide-dept-8002
  build.version: 1.0-SNAPSHOT