server:
  port: 3333

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AllureCode/microservicecloud-config.git #GitHub上面的git仓库SSH地址
