server:
  port: 9527
#配置微服务名称
spring:
  application:
    name: microservicecloud-zuul-gateway
#配置eureka
eureka:
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
#eureka对info信息的改善
info:
  app.name: gnawococ-microservicecloud
  company.name: www.gnawococ.com
  build.artifactId: $project.artifactId$
#配置zuul的路由访问规则
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  #ignored-services: microservicecloud-dept #忽略真实的微服务名称 采用mydept代替
  ignored-services: "*" #忽略所有真实的微服务名称
  prefix: /gnawococ #添加公共前缀